// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdFqP7T4fbTg2deaZhRwjA7hBCHqItc5U',
    appId: '1:691412463331:web:95b745211f1fb743b29fd6',
    messagingSenderId: '691412463331',
    projectId: 'learnovaapp-6ebbc',
    authDomain: 'learnovaapp-6ebbc.firebaseapp.com',
    storageBucket: 'learnovaapp-6ebbc.firebasestorage.app',
    measurementId: 'G-128QBR1B4T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYKEfJpIHpSlqvZ1-ZnSooZczs_Wtav08',
    appId: '1:691412463331:android:7bcf5e66ae86c682b29fd6',
    messagingSenderId: '691412463331',
    projectId: 'learnovaapp-6ebbc',
    storageBucket: 'learnovaapp-6ebbc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqGKNyQUqhTRD8KW1871KWL04xrugdzfc',
    appId: '1:691412463331:ios:aecf0b1b3a37e85fb29fd6',
    messagingSenderId: '691412463331',
    projectId: 'learnovaapp-6ebbc',
    storageBucket: 'learnovaapp-6ebbc.firebasestorage.app',
    iosClientId: '691412463331-nmfp1r5jdsuoh0lq2ji0tsgfdo09jfus.apps.googleusercontent.com',
    iosBundleId: 'com.example.learnovaapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqGKNyQUqhTRD8KW1871KWL04xrugdzfc',
    appId: '1:691412463331:ios:aecf0b1b3a37e85fb29fd6',
    messagingSenderId: '691412463331',
    projectId: 'learnovaapp-6ebbc',
    storageBucket: 'learnovaapp-6ebbc.firebasestorage.app',
    iosClientId: '691412463331-nmfp1r5jdsuoh0lq2ji0tsgfdo09jfus.apps.googleusercontent.com',
    iosBundleId: 'com.example.learnovaapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdFqP7T4fbTg2deaZhRwjA7hBCHqItc5U',
    appId: '1:691412463331:web:8ebc64e6b35ecf94b29fd6',
    messagingSenderId: '691412463331',
    projectId: 'learnovaapp-6ebbc',
    authDomain: 'learnovaapp-6ebbc.firebaseapp.com',
    storageBucket: 'learnovaapp-6ebbc.firebasestorage.app',
    measurementId: 'G-J9VZ201PR7',
  );
}
